version: "3.3"
services:
  backend-mongo:
    container_name: container-jdk17
    image: backendmongo:v1.0
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile            
    ports:
      - 8081:8081
    environment:
      server.port: 8081
    volumes:
      - ./:/app    
    networks:
       - backendmongo
      
networks:                     
    backendmongo:
